export const INVOICE_FREQUENCY = {
  YEARLY: 'YEARLY',
  BI_ANNUALLY: 'BI_ANNUALLY',
  QUARTERLY: 'QUARTERLY',
  MONTHLY: 'MONTHLY',
  BI_MONTHLY: 'BI_MONTHLY',
  WEEKLY: 'WEEKLY',
  MONTH_1: 'MONTH_1',
  MONTH_15: 'MONTH_15',
  MONTH_1_15: 'MONTH_1_15',
  CUSTOM_DATES: 'CUSTOM_DATES',
  EVERY_X_DAY: 'EVERY_X_DAY'
};
